# Generated by Django 4.1.7 on 2023-04-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
