# Generated by Django 4.1.7 on 2023-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_investors',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_raised',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
