# Generated by Django 4.1.7 on 2023-09-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mynt_users', '0005_myntusers_secondary_email_and_more'),
        ('campaign', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('investor_first_name', models.CharField(max_length=60, null=True)),
                ('investor_last_name', models.CharField(max_length=60, null=True)),
                ('investor_email', models.CharField(max_length=100, null=True)),
                ('investor_mobile_number', models.CharField(max_length=20, null=True)),
                ('applied_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynt_users.myntusers')),
            ],
        ),
    ]
