# Generated by Django 4.1.7 on 2023-04-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_initial'),
        ('mynt_users', '0002_alter_myntusers_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cashfree_order_id', models.CharField(max_length=20, null=True)),
                ('mynt_order_id', models.CharField(max_length=40, null=True)),
                ('amount', models.CharField(max_length=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('payment_session_id', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynt_users.myntusers')),
            ],
        ),
    ]
