# Generated by Django 4.1.7 on 2023-04-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
