# Generated by Django 4.1.7 on 2024-08-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_payment_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
