# Generated by Django 4.1.7 on 2023-02-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mynt_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorConsent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('risk_consent', models.BooleanField(default=False)),
                ('limited_transfer_consent', models.BooleanField(default=False)),
                ('diversification_consent', models.BooleanField(default=False)),
                ('cancellation_consent', models.BooleanField(default=False)),
                ('research_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynt_users.myntusers')),
            ],
        ),
    ]
