# Generated by Django 4.1.7 on 2023-02-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynt_users', '0001_initial'),
        ('investor_consent', '0002_alter_investorconsent_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorconsent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynt_users.myntusers'),
        ),
    ]
