# Generated by Django 4.1.7 on 2023-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyntUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('email_otp', models.CharField(default=None, max_length=6, null=True)),
                ('social_login', models.BooleanField(default=False)),
                ('country', models.CharField(default=None, max_length=100, null=True)),
                ('nationality', models.CharField(default=None, max_length=100, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('profile_image', models.TextField(default=None, null=True)),
                ('user_type', models.CharField(choices=[('INVESTOR', 'INVESTOR'), ('FOUNDER', 'FOUNDER')], default='INVESTOR', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
