# Generated by Django 4.1.7 on 2023-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynt_users', '0003_myntusers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myntusers',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
