# Generated by Django 4.1.7 on 2023-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynt_users', '0004_alter_myntusers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='myntusers',
            name='secondary_email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntusers',
            name='secondary_email_otp',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='myntusers',
            name='secondary_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
