# Generated by Django 4.1.7 on 2023-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTerms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('security_type', models.CharField(choices=[('CSOP', 'CSOP'), ('CCD', 'CCD'), ('NCD', 'NCD'), ('ID', 'ID')], default='CSOP', max_length=20)),
                ('discount', models.CharField(max_length=2)),
                ('valuation_cap', models.CharField(max_length=12)),
                ('min_subscription', models.CharField(max_length=12)),
                ('target', models.CharField(max_length=12)),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
