# Generated by Django 4.1.7 on 2023-03-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_type', '0001_initial'),
        ('deal_terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealterms',
            name='security_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal_type.dealtype'),
        ),
    ]
