# Generated by Django 4.1.7 on 2023-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_terms', '0002_alter_dealterms_security_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealterms',
            name='discount',
            field=models.CharField(max_length=3),
        ),
    ]
