# Generated by Django 4.1.7 on 2023-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_terms', '0003_alter_dealterms_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealterms',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealterms',
            name='account_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealterms',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealterms',
            name='enable_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealterms',
            name='ifsc_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
