# Generated by Django 4.1.7 on 2023-02-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mynt_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorKyc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pan_card', models.CharField(max_length=10, null=True)),
                ('pan_card_verified', models.BooleanField(default=False)),
                ('birth_date', models.CharField(max_length=2, null=True)),
                ('birth_month', models.CharField(max_length=2, null=True)),
                ('birth_year', models.CharField(max_length=4, null=True)),
                ('address_line_1', models.CharField(max_length=100, null=True)),
                ('address_line_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(default='India', max_length=50)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('bank_account', models.CharField(max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=50, null=True)),
                ('bank_account_verified', models.BooleanField(default=False)),
                ('linkedin_profile', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynt_users.myntusers')),
            ],
        ),
    ]
