# Generated by Django 4.1.7 on 2023-02-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorkyc',
            name='birth_date',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='investorkyc',
            name='birth_month',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='investorkyc',
            name='birth_year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
