# Generated by Django 4.1.7 on 2023-02-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_kyc', '0002_alter_investorkyc_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorkyc',
            name='pan_card',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
