# Generated by Django 4.1.7 on 2023-02-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_kyc', '0003_alter_investorkyc_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorkyc',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investorkyc',
            name='mobile_number_otp',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='investorkyc',
            name='mobile_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
