# Generated by Django 4.1.7 on 2023-02-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_kyc', '0004_investorkyc_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorkyc',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
