# Generated by Django 4.1.7 on 2023-03-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_kyc', '0005_investorkyc_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorkyc',
            name='aadhar_card_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='investorkyc',
            name='aadhar_card_verified',
            field=models.BooleanField(default=False),
        ),
    ]
