# Generated by Django 4.1.7 on 2023-03-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_kyc', '0006_investorkyc_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorkyc',
            old_name='aadhar_card_number',
            new_name='aadhaar_card_number',
        ),
        migrations.RenameField(
            model_name='investorkyc',
            old_name='aadhar_card_verified',
            new_name='aadhaar_card_verified',
        ),
    ]
