# Generated by Django 4.1.7 on 2023-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('AGREEMENTS', 'AGREEMENTS'), ('DOCUMENTS', 'DOCUMENTS')], default='DOCUMENTS', max_length=12)),
                ('document_name', models.CharField(max_length=100)),
                ('agreement_status', models.CharField(choices=[('UPLOADED BY ADMIN', 'UPLOADED BY ADMIN'), ('SIGNED BY FOUNDER', 'SIGNED BY FOUNDER'), ('SIGNED BY ADMIN', 'SIGNED BY ADMIN')], max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
