# Generated by Django 4.1.7 on 2023-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_url',
            field=models.TextField(null=True),
        ),
    ]
