# Generated by Django 4.1.7 on 2023-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documents_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='contract_id',
            field=models.TextField(null=True),
        ),
    ]
