# Generated by Django 4.1.7 on 2023-09-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealtype',
            name='deal_description',
            field=models.TextField(null=True),
        ),
    ]
