# Generated by Django 4.1.7 on 2023-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_type', '0002_dealtype_deal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealtype',
            name='deal_tagline',
            field=models.TextField(null=True),
        ),
    ]
