# Generated by Django 4.1.7 on 2023-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mynt_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_logo', models.TextField(default=None)),
                ('founder_linked_in_profile', models.TextField(default=None)),
                ('company_name', models.CharField(default=None, max_length=100)),
                ('company_linked_in_profile', models.TextField(default=None)),
                ('website_url', models.TextField(default=None)),
                ('previous_funding', models.TextField(default=None)),
                ('product_description', models.TextField(default=None)),
                ('traction_description', models.TextField(default=None)),
                ('revenue', models.CharField(default='0', max_length=12)),
                ('reason_for_community_round', models.TextField(default=None)),
                ('reason_for_mynt', models.TextField(default=None)),
                ('existing_commitments', models.TextField(default=None)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('company_address', models.TextField(null=True)),
                ('facebook_link', models.TextField(null=True)),
                ('instagram_link', models.TextField(null=True)),
                ('legal_name', models.CharField(max_length=100, null=True)),
                ('cin', models.CharField(max_length=22, null=True)),
                ('date_of_incorporation', models.DateField(null=True)),
                ('incorporation_type', models.CharField(max_length=50, null=True)),
                ('sector', models.CharField(max_length=50, null=True)),
                ('invested_so_far', models.CharField(max_length=12, null=True)),
                ('number_of_employees', models.CharField(max_length=5, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynt_users.myntusers')),
            ],
        ),
    ]
