# Generated by Django 4.1.7 on 2023-03-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_pitch',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', max_length=20),
        ),
    ]
