# Generated by Django 4.1.7 on 2023-03-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='revenue',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
