# Generated by Django 4.1.7 on 2023-09-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
