# Generated by Django 4.1.7 on 2023-10-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mynt_users', '0005_myntusers_secondary_email_and_more'),
        ('campaign', '0003_campaign_total_investors_campaign_total_raised'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agreement_status', models.CharField(choices=[('UPLOADED BY FOUNDER', 'UPLOADED BY FOUNDER'), ('SIGNED BY INVESTOR', 'SIGNED BY INVESTOR'), ('SIGNED BY FOUNDER', 'SIGNED BY FOUNDER')], max_length=200, null=True)),
                ('agreement_url', models.TextField(null=True)),
                ('agreement_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynt_users.myntusers')),
            ],
        ),
    ]
